import React, { useState } from 'react';
import { Head, Link } from '@inertiajs/react';
import PublicNavbar from '@/Components/PublicNavbar';
import PublicFooter from '@/Components/PublicFooter';
import CurrencySwitcher from '@/Components/CurrencySwitcher';
import { 
    HelpCircle, Mail, FileText, Building2, ChevronDown, Sparkles, 
    ShieldCheck, Wallet, ArrowRight, RefreshCw, CheckCircle2 
} from 'lucide-react';

const SUPPORT_FAQS = [
    {
        q: "How does the 14-Day Refund Guarantee on wallet top-ups work?",
        a: "Under UK Consumer and B2B Regulations, any unspent funds in your Voltoria AI wallet can be refunded in full within 14 calendar days of deposit. Simply contact support at info@voltoria.co.uk with your transaction reference ID."
    },
    {
        q: "Are the VAT invoices compliant for European and UK corporate accounting?",
        a: "Yes. Every invoice issued by INCHWARD LIMITED includes our UK Company Registration number (16021412), an official PAID & VERIFIED timestamp, and applies the 0% VAT UK B2B Reverse Charge mechanism."
    },
    {
        q: "Who owns the Intellectual Property (IP) of generated plans and dossiers?",
        a: "You retain 100% of all intellectual property, proprietary financial models, and factory negotiation scripts generated by our platform. Voltoria AI claims zero equity or royalties on your business venture."
    },
    {
        q: "Can I upgrade or customize a generated brief after downloading?",
        a: "Yes. All projects remain securely stored in your personal Dashboard. You can revisit your project at any time, copy JSON structured models, export new PDF variants, or run updated parameters."
    },
    {
        q: "What is the difference between our 6 pricing tiers (€589 to €6,999)?",
        a: "Starter (€589) provides concept validation & TAM sizing. Seed (€989) adds 4-page P&L models. Pro Venture (€1,489) unlocks the 6-page institutional PDF with unit economics & RFQ scripts. Scaleup (€2,499) adds 8-page multi-scenario modeling & Cap Table. Syndicate (€4,299) adds customs freight & due diligence suites. Enterprise (€6,999) provides full white-label architecture & 24/7 dedicated SLA support."
    },
    {
        q: "What format are the final documents delivered in?",
        a: "Documents are rendered in high-resolution vector PDF format via our DomPDF engine. They contain zero watermarks upon payment/deduction, and are formatted according to international venture capital standards."
    }
];

export default function Support() {
    const [openFaq, setOpenFaq] = useState(0);

    return (
        <div className="min-h-screen bg-slate-950 text-slate-100 font-sans antialiased selection:bg-indigo-500 selection:text-white relative overflow-hidden">
            <Head title="Support & Help Desk — Voltoria AI" />

            <PublicNavbar />

            {/* Ambient Radial Glows */}
            <div className="absolute top-20 left-1/2 -translate-x-1/2 w-[900px] h-[450px] bg-indigo-600/15 blur-3xl pointer-events-none -z-10" />

            <div className="max-w-7xl mx-auto px-4 sm:px-6 py-16 space-y-16">
                {/* Header */}
                <div className="text-center space-y-3 max-w-2xl mx-auto">
                    <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-cyan-500/10 border border-cyan-500/30 text-cyan-300 text-xs font-bold uppercase tracking-wider">
                        <HelpCircle className="w-3.5 h-3.5" /> 24/7 Client Knowledge Base
                    </div>
                    <h1 className="text-3xl sm:text-5xl font-extrabold text-white tracking-tight">
                        Support & Help Desk
                    </h1>
                    <p className="text-sm text-slate-300">
                        Everything you need to know about our provisioning architecture, wallet billing, B2B tax compliance, and document exports.
                    </p>
                </div>

                {/* 3 Support Channel Cards */}
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6 max-w-5xl mx-auto">
                    {/* 1. Executive Email */}
                    <div className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 backdrop-blur-xl flex flex-col justify-between space-y-4 hover:border-slate-700 transition-all">
                        <div className="space-y-3">
                            <div className="w-10 h-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
                                <Mail className="w-5 h-5" />
                            </div>
                            <h3 className="font-extrabold text-white text-base">Executive Email Desk</h3>
                            <p className="text-xs text-slate-400 leading-relaxed">
                                Direct communication with our technical support and accounting specialists.
                            </p>
                        </div>
                        <a
                            href="mailto:info@voltoria.co.uk"
                            className="inline-flex items-center gap-1.5 text-xs font-bold text-indigo-400 hover:text-indigo-300 transition-colors"
                        >
                            info@voltoria.co.uk <ArrowRight className="w-3.5 h-3.5" />
                        </a>
                    </div>

                    {/* 2. B2B Invoices & Wallet */}
                    <div className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 backdrop-blur-xl flex flex-col justify-between space-y-4 hover:border-slate-700 transition-all">
                        <div className="space-y-3">
                            <div className="w-10 h-10 rounded-xl bg-emerald-500/10 border border-emerald-500/20 flex items-center justify-center text-emerald-400">
                                <Wallet className="w-5 h-5" />
                            </div>
                            <h3 className="font-extrabold text-white text-base">B2B Invoices & Wallet</h3>
                            <p className="text-xs text-slate-400 leading-relaxed">
                                Inspect your wallet transactions, top up balance, and download official PDF tax invoices.
                            </p>
                        </div>
                        <Link
                            href="/dashboard"
                            className="inline-flex items-center gap-1.5 text-xs font-bold text-emerald-400 hover:text-emerald-300 transition-colors"
                        >
                            Go to Dashboard <ArrowRight className="w-3.5 h-3.5" />
                        </Link>
                    </div>

                    {/* 3. Corporate Inquiries */}
                    <div className="bg-slate-900/80 border border-slate-800 rounded-3xl p-6 backdrop-blur-xl flex flex-col justify-between space-y-4 hover:border-slate-700 transition-all">
                        <div className="space-y-3">
                            <div className="w-10 h-10 rounded-xl bg-cyan-500/10 border border-cyan-500/20 flex items-center justify-center text-cyan-400">
                                <Building2 className="w-5 h-5" />
                            </div>
                            <h3 className="font-extrabold text-white text-base">Corporate Inquiries</h3>
                            <p className="text-xs text-slate-400 leading-relaxed">
                                Submit a structured support ticket with guaranteed response within 24–48 business hours.
                            </p>
                        </div>
                        <Link
                            href="/contact"
                            className="inline-flex items-center gap-1.5 text-xs font-bold text-cyan-400 hover:text-cyan-300 transition-colors"
                        >
                            Open Support Ticket <ArrowRight className="w-3.5 h-3.5" />
                        </Link>
                    </div>
                </div>

                {/* FAQ Accordion Section */}
                <div className="max-w-3xl mx-auto space-y-8">
                    <div className="text-center space-y-2">
                        <h2 className="text-2xl sm:text-3xl font-extrabold text-white">Frequently Answered Questions</h2>
                        <p className="text-xs text-slate-400">Clear answers to your legal, financial, and technical inquiries.</p>
                    </div>

                    <div className="space-y-3">
                        {SUPPORT_FAQS.map((faq, idx) => {
                            const isOpen = openFaq === idx;
                            return (
                                <div key={idx} className="bg-slate-900/60 border border-slate-800 rounded-2xl overflow-hidden transition-colors">
                                    <button
                                        onClick={() => setOpenFaq(isOpen ? -1 : idx)}
                                        className="w-full p-5 text-left flex items-center justify-between gap-4 text-sm font-bold text-white hover:text-indigo-400 transition-colors"
                                    >
                                        <span>{faq.q}</span>
                                        <ChevronDown className={`w-4 h-4 shrink-0 transition-transform duration-200 ${isOpen ? 'rotate-180 text-indigo-400' : 'text-slate-500'}`} />
                                    </button>
                                    {isOpen && (
                                        <div className="px-5 pb-5 text-xs text-slate-300 leading-relaxed border-t border-slate-800/80 pt-3 animate-in fade-in duration-150">
                                            {faq.a}
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>
                </div>
            </div>

            <PublicFooter />
            <CurrencySwitcher floating={true} />
        </div>
    );
}
